## Frozen test generated by `freeze_scenario` (ticket #13) from the session
## trace kept by the MCP server — each selector was re-verified
## against the live game at generation time (see freeze.ts
## verifySelectorsLive). Replayed without AI by the addon's runner:
##
##     godot --headless --path . res://addons/playtest/runner.tscn -- --suite=res://playtests/
extends PlaytestCase

func test_tps_demo_player_moves_and_neutralizes_a_robot() -> void:
	await start_game("res://level/level.tscn")

	await wait_for({"test_id": "player_1"}, {"timeout_ms": 30000})
	# Right after the player has spawned, nothing has moved yet: a `now` check.
	await assert_now_property({"test_id": "enemy_Marker3D1"}, "health", 5, "initial HP")
	input({"type": "action", "action": "move_forward", "pressed": true})
	await time_frames(120, true)
	input({"type": "action", "action": "move_forward", "pressed": false})
	# Post-movement: `has_moved` settles as physics integrates over the
	# 120 frames above, an `eventually` check.
	await assert_eventually_property({"test_id": "player_1"}, "has_moved", true, "player traveled >= 2m")
	invoke({"test_id": "enemy_Marker3D1"}, "hit", [])
	invoke({"test_id": "enemy_Marker3D1"}, "hit", [])
	invoke({"test_id": "enemy_Marker3D1"}, "hit", [])
	invoke({"test_id": "enemy_Marker3D1"}, "hit", [])
	invoke({"test_id": "enemy_Marker3D1"}, "hit", [])
	# Post-neutralization: `hit()` may itself take a frame or more to
	# propagate (RPC/coroutine, see dogfooding/FRICTIONS.md #2), `eventually`.
	await assert_eventually_property({"test_id": "enemy_Marker3D1"}, "health", 0, "robot neutralized (HP)")
	await assert_eventually_property({"test_id": "enemy_Marker3D1"}, "dead", true, "robot neutralized (dead)")
